#!/bin/bash

# 完整部署脚本 - Cloudflare Pages + Workers

echo "🚀 工具合集网站完整部署指南"
echo "================================"

echo ""
echo "📋 部署前检查清单："
echo "✅ Node.js 版本 >= 20.0.0 (当前: $(node --version))"
echo "✅ Wrangler CLI 已安装"
echo "✅ GitHub 仓库已创建"
echo "✅ Cloudflare 账号已注册"

echo ""
echo "🌐 第一步：部署后端 (Cloudflare Workers)"
echo "---------------------------------------"
echo "1. 登录 Cloudflare："
echo "   wrangler login"
echo ""
echo "2. 执行 Workers 部署脚本："
echo "   ./deploy/workers.sh"
echo ""
echo "3. 记录生成的 Worker URL，格式如下："
echo "   https://toolkit-api.your-subdomain.workers.dev"

echo ""
echo "📄 第二步：部署前端 (Cloudflare Pages)"
echo "-------------------------------------"
echo "1. 推送代码到 GitHub："
echo "   git remote add origin https://github.com/yourusername/your-repo.git"
echo "   git push origin main"
echo ""
echo "2. 访问 Cloudflare Pages："
echo "   https://pages.cloudflare.com/"
echo ""
echo "3. 连接 GitHub 仓库并配置："
echo "   - 框架预设：Vue"
echo "   - 构建命令：npm run build"
echo "   - 输出目录：dist"
echo "   - Node.js 版本：22.x"

echo ""
echo "⚙️ 第三步：配置环境变量"
echo "------------------------"
echo "1. 在 Cloudflare Pages 设置中添加环境变量："
echo "   VITE_API_URL=https://toolkit-api.your-subdomain.workers.dev"
echo ""
echo "2. 重新部署前端以应用环境变量"

echo ""
echo "✅ 第四步：验证部署"
echo "-------------------"
echo "1. 访问前端 URL 确认网站正常"
echo "2. 测试工具功能（如文本去重）"
echo "3. 检查 API 连接状态"
echo "4. 验证响应式设计"

echo ""
echo "🎉 部署完成！"
echo "==============="
echo "你的工具网站现在可以在以下地址访问："
echo "- 前端: https://your-project.pages.dev"
echo "- API: https://toolkit-api.your-subdomain.workers.dev"
echo ""
echo "📱 支持功能："
echo "- 🎨 现代化 UI 设计"
echo "- 📱 响应式布局"
echo "- 🔧 实用工具功能"
echo "- 📊 使用统计"
echo "- 🌐 全球 CDN 加速"

# 检查部署状态
echo ""
echo "🔍 快速检查脚本："
echo "# 检查 API 状态"
echo "curl https://your-api-url.workers.dev/api/health"
echo ""
echo "# 检查前端构建"
echo "npm run build"
echo ""
echo "# 测试本地环境"
echo "npm run dev"